/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "psmqkttawkpozgzvuwnl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbXFrdHRhd2twb3pnenZ1d25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MTg0NzksImV4cCI6MjA4NDE5NDQ3OX0.51SjrIuJAqq3DAn-sOjaNf84s0fwzblU8j-ReQpDQaA"